In [89]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')


In [90]:
tsts_m =  np.random.uniform(-5, 5, size = (50, 2)) 

In [4]:
tsts_m.shape[1]

2

In [6]:
tsts_m[:, 0]

array([ 3.7330996 , -2.24833648, -3.74948083,  1.63370819, -1.33649809,
       -4.47964875,  1.54098434,  1.65678909, -1.3896636 , -1.6516846 ,
       -4.07066589,  2.46949435,  2.11947977,  4.17046557,  1.82690865,
       -3.04094511,  2.18119291,  4.16726783,  2.93195192,  2.334503  ,
        1.61806116, -4.51049905, -0.12863673, -2.99407772, -1.96799799,
        0.42512041,  0.24050502,  3.65473408, -1.48601195, -1.04188159,
        2.94026447,  4.00482086, -1.91597103, -3.17005738,  0.24344872,
        4.57063563, -0.56380721,  2.77900327,  2.73017261, -4.24597753,
        4.52417465, -3.47161969,  3.37871724, -3.02293148,  2.78337456,
       -3.02245691,  1.54882998, -0.7581558 ,  3.40634936, -1.90936499])

In [5]:
np.random.choice(tsts_m[:, 0])

np.float64(-1.6516845969970007)

In [7]:
np.random.rand(1)

array([0.30695029])

In [108]:
def HS_algorithm(HMS, HMCR, PAR, BW, lower_bound, upper_bound,f, iterations, dimension, task = 'max'):
    
    ## initialize population of size HM
    HM = np.random.uniform(lower_bound, upper_bound, size = (HMS, dimension)) 
    # calculate fitness value for all particles
    
    F = np.apply_along_axis(f, 1, HM)
    
    if task == 'max':
        best_idx = F.argmax()
        historic_best = HM[best_idx]
    else:
        best_idx = F.argmin()
        historic_best = HM[best_idx]
    t = 0
    while t < iterations:
        
        if task == 'max':
            worst_idx = F.argmin()
            worst_obj_value = F[F.argmin()]
        else:
            worst_idx = F.argmax()
            worst_obj_value = F[F.argmax()]
            
        new_harmony = np.zeros(dimension)

        for d in range(dimension):
            r1, r2 = np.random.rand(2) ## 2 numbers between 0 and 1
            
            if r1 < HMCR:
                new_harmony[d] = np.random.choice(HM[:, d])
                if r2 < PAR:
                     new_harmony[d] += (np.random.rand(1) *BW)
            else:
                 new_harmony[d] = lower_bound + ((upper_bound - lower_bound)*np.random.rand(1))
                
        F_new = f(new_harmony)
            
        if task == 'max':
            if F_new > worst_obj_value:
                HM[worst_idx] = new_harmony
        else:
            if F_new < worst_obj_value:
                HM[worst_idx] = new_harmony


        F[worst_idx] = F_new
        
        if task == 'max':
            best_idx = F.argmax()
            historic_best = HM[best_idx]
            historic_best_obj = F[best_idx]
        else:
            best_idx = F.argmin()
            historic_best = HM[best_idx]
            historic_best_obj = F[best_idx]
        
        t += 1

    
    return historic_best, historic_best_obj

In [109]:
def beale(X):
    return ((1.5 - X[0] + (X[0]*X[1]))**2)  + ((2.25 - X[0]+(X[0]*(X[1]**2)))**2)+ ((2.625-X[0]+(X[0]*(X[1]**3)))**2)

## valor optimo 3,.5, f = 0
beale([3, 0.5])

0.0

In [110]:
from timeit import default_timer as timer

In [156]:
start = timer()
# HS_algorithm(HMS, HMCR, PAR, BW, lower_bound, upper_bound,f, iterations, dimension, task = 'max')
print(HS_algorithm(200, 0.95, 0.3,0.1, -100,100, beale, 1000,2, task = 'min'))
stop = timer()
execution_time = stop - start
print(execution_time)

(array([3.00640603, 0.52595281]), np.float64(0.01439646595261806))
0.13694309999846155


In [185]:
def McCormick(X):
    return np.sin(X[0]+X[1]) + (X[0]-X[1])**2 - 1.5 * X[0] + 2.5 *X[1]+1

In [186]:
McCormick([-0.54719,-1.54719])

np.float64(-1.913222954882274)

In [191]:
start = timer()
# HS_algorithm(HMS, HMCR, PAR, BW, lower_bound, upper_bound,f, iterations, dimension, task = 'max')

print(HS_algorithm(600, 0.8, 0.1,0.1, -3, 4, McCormick, 500, 2 ,task = 'min'))

stop = timer()
execution_time = stop - start
print(execution_time)

(array([-0.5927954 , -1.49005514]), np.float64(-1.9026095565306087))
0.0431825999985449


In [193]:
def himm(X):
    return ((X[0]**2+X[1]-11)**2) + ((X[0]+(X[1]**2)-7)**2 )
himm([-0.270845,-0.923039])

181.61652152257642

In [194]:
start = timer()
# HS_algorithm(HMS, HMCR, PAR, BW, lower_bound, upper_bound,f, iterations, dimension, task = 'max')

print(HS_algorithm(100, 0.8, 0.1,0.1, -1, 1, himm, 500, 2 ,task = 'max'))

stop = timer()
execution_time = stop - start
print(execution_time)

(array([-0.29094039, -0.92548518]), np.float64(181.6071946219211))
0.07694769999943674
