In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
def firefly_algorithm(population, gamma, beta_zero, alpha_zero, delta, lower_bound, upper_bound, f, iterations, dimension, task='max'):
    scale = abs(upper_bound - lower_bound)

    # Initialize firefly positions
    positions = np.random.uniform(lower_bound, upper_bound, size=(population, dimension))
    I = np.apply_along_axis(f, 1, positions)

    if task == 'max':
        best_idx = I.argmax()
    else:
        best_idx = I.argmin()

    historic_best = positions[best_idx]
    historic_best_obj = I[best_idx]

    t = 0
    while t < iterations:
        for i in range(population):
            for j in range(population):
                if i == j:
                    continue

                if (task == 'max' and I[i] < I[j]) or (task == 'min' and I[i] > I[j]):
                    rij = np.linalg.norm(positions[i] - positions[j])

                    attraction = beta_zero * np.exp(-gamma * rij)
                    random_step = alpha_zero * delta * (np.random.rand(dimension) - 0.5) * scale

                    new_position = positions[i] + attraction * (positions[j] - positions[i]) + random_step

                    # Keep new position within bounds
                    new_position = np.clip(new_position, lower_bound, upper_bound)

                    new_f = f(new_position)

                    if (task == 'max' and new_f > I[i]) or (task == 'min' and new_f < I[i]):
                        positions[i] = new_position
                        I[i] = new_f

        if task == 'max':
            best_idx = I.argmax()
        else:
            best_idx = I.argmin()

        historic_best = positions[best_idx]
        historic_best_obj = I[best_idx]

        t += 1

    return historic_best, historic_best_obj

In [3]:
def beale(X):
    return ((1.5 - X[0] + (X[0]*X[1]))**2)  + ((2.25 - X[0]+(X[0]*(X[1]**2)))**2)+ ((2.625-X[0]+(X[0]*(X[1]**3)))**2)

## valor optimo 3,.5, f = 0
beale([3, 0.5])

0.0

In [4]:
from timeit import default_timer as timer

In [5]:
start = timer()
# firefly_algorithm(population, gamma, beta_zero,  alpha_zero, delta,lower_bound, upper_bound,f, iterations, dimension, task = 'max')
#population, gamma, beta_zero, alpha_zero, delta, lower_bound, upper_bound, f, iterations, dimension, task='max'
print(firefly_algorithm(100, 0.01, 1, 1, 0.9, -100, 100, beale, 100, 2 ,task = 'min'))
stop = timer()
execution_time = stop - start
print(execution_time)

(array([2.53339074, 0.3355404 ]), np.float64(0.06870218938014791))
20.130532400002267


In [6]:
def McCormick(X):
    return np.sin(X[0]+X[1]) + (X[0]-X[1])**2 - 1.5 * X[0] + 2.5 *X[1]+1

In [8]:
start = timer()
# firefly_algorithm(population, gamma, beta_zero,  alpha_zero, delta,lower_bound, upper_bound,f, iterations, dimension, task = 'max')
#population, gamma, beta_zero, alpha_zero, delta, lower_bound, upper_bound, f, iterations, dimension, task='max'
print(firefly_algorithm(100, 0.01, 1, 1, 0.9, -3, 4, McCormick, 100, 2 ,task = 'min'))
stop = timer()
execution_time = stop - start
print(execution_time)

(array([-0.54400481, -1.54269241]), np.float64(-1.913195535499134))
26.749691999997594


In [9]:
def himm(X):
    return ((X[0]**2+X[1]-11)**2) + ((X[0]+(X[1]**2)-7)**2 )
himm([-0.270845,-0.923039])

181.61652152257642

In [11]:
start = timer()
# firefly_algorithm(population, gamma, beta_zero,  alpha_zero, delta,lower_bound, upper_bound,f, iterations, dimension, task = 'max')
#population, gamma, beta_zero, alpha_zero, delta, lower_bound, upper_bound, f, iterations, dimension, task='max'
print(firefly_algorithm(100, 0.01, 1, 1, 0.9, -1, 1, himm, 100, 2 ,task = 'max'))
stop = timer()
execution_time = stop - start
print(execution_time)

(array([-0.27147197, -0.92199401]), np.float64(181.6165066311311))
23.810970999998972
